name: Dynamic README Update Workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 15 * * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:
jobs:
  update-readme-contents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Let the magic happen
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn

      - run: node .

      - name: Add to git repo
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "AkshayHere"
          git config --global user.email "akshymohn@gmail.com"
          git commit -m "[Automated] README updated with new Office quote!"
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

