name: Dynamic README Update Workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 15 * * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Generate README content
        run: node .

      - name: Commit changes
        run: |
          git config --global user.name "AkshayHere"
          git config --global user.email "akshymohn@gmail.com"
          git add .
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "[Automated] README updated with new Office quote!"

      - name: Push changes
        run: git push
